### ISSUE TITLE
configure docs application server to support SPA

### ISSUE THREAD

**Issue by theenadayalank** [kishoreyuvan/ember-key-navigation#9]
They deployed docs page is built as a single page application. but the server is not configured for the same. 

The URL `https://kishoreyuvan.github.io/ember-key-navigation/docs/` is not loaded since the server looks for a `docs/index.html` or `docs.html` which is not available in our case.

**Comment by kishoreyuvan** [comment]
Thanks @theenadayalank for noted down.

**Comment by kishoreyuvan** [comment]
Fixed in https://github.com/kishoreyuvan/ember-key-navigation/commit/0620c3a0d7f5cba06685ca607ec957b59e41dce7
